# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Onkur Sen"

# URL
baseurl:            "http://onkursen.github.io/quest"
permalink:          /:categories/:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
